version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: food-ordering-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fooddb
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: food-ordering-backend
    ports:
      - '9090:9090'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fooddb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: food-ordering-frontend
    ports:
      - '4200:80'
    depends_on:
      - backend

volumes:
  db_data:
